---
- name: smartd service configuration
  lineinfile:
    create: yes
    dest: /etc/default/smartmontools
    state: present
    regexp: "^#?{{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - {key: "start_smartd", value: "yes"}
    - {key: "smartd_opts", value: "'-p /var/run/smartd.pid -i 600 -A /var/log/smartd/'"}
  notify: smartd restart

- name: smartd log directory
  file:
    path: /var/log/smartd
    state: directory
  notify: smartd restart

- name: smartd logrotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/smartd

- name: smartd config
  template:
    src: smartd.j2
    dest: /etc/smartd.conf
  register: smartd_config
  notify:
    - smartd restart
