---
- name: gather required facts
  setup:
    gather_subset: [virtual]
  when: ansible_virtualization_type is not defined

- name: install
  include_tasks: install.yml
  when: smartd_setup == "full" and (ansible_virtualization_type != 'lxc' or smartd_role_test_mode)

- name: configure
  import_tasks: configure.yml
  when: ansible_virtualization_type != 'lxc' or smartd_role_test_mode

- name: test alert
  include_tasks: test-alert.yml
  when: smartd_config.changed|bool and smartd_test_alert and (ansible_virtualization_type != 'lxc' or smartd_role_test_mode)
